/**
 * @attensira/analytics — signed edge/server client for `POST /v1/visits`.
 *
 * MIT-553: the package previously beaconed page hits from the browser to
 * `https://ingest.attensira.com/v1/crawler-logs`, a host the webapp never
 * served — nothing sent by that build was ever recorded. This is a rewrite
 * against the endpoint that actually exists: `attensira/webapp`'s
 * `POST /v1/visits` (see `src/internal/aitraffic/ingest.go`), HMAC-signed
 * and edge-only.
 *
 * Why this cannot be a browser SDK: the endpoint is authenticated by an
 * HMAC over the request body, keyed by a per-project signing secret. A
 * secret shipped to a browser bundle is a secret anyone viewing page
 * source can read, which defeats the signature entirely — the whole reason
 * `/v1/visits` uses a signature instead of a bearer key is that its caller
 * (a CDN worker on the customer's own domain) has nowhere safe to keep one.
 * AI crawlers don't execute JavaScript either way, so a browser beacon
 * never saw them regardless of the signing question. This package now only
 * runs where the secret can stay a secret: an edge worker, Next.js
 * middleware, or any other server-side runtime with `fetch` and
 * `crypto.subtle`.
 *
 * Get `projectId` and `signingSecret` from `GET /v1/visits/install` on your
 * workspace's API key. `signingSecret` there is the project-derived secret
 * (`signing_secret` in that response) — not your API key, and not the
 * webapp's root `AI_TRAFFIC_SIGNING_KEY`, which never leaves the server.
 */

const DEFAULT_ENDPOINT = 'https://api.attensira.com/v1/visits';
const SIGNATURE_HEADER = 'X-Attensira-Signature';

function assertServerSide(): void {
  if (typeof window !== 'undefined') {
    throw new Error(
      '[@attensira/analytics] refusing to run in a browser: this package signs ' +
        'every request with your project signing secret, and a secret reachable ' +
        'from client-side JavaScript is a secret anyone viewing page source can ' +
        'read. Call it from edge middleware or a server route instead — see the ' +
        'README for Cloudflare Workers / Next.js middleware examples.'
    );
  }
}

// -- public types -----------------------------------------------------------

/** One page hit as this client saw it. Mirrors `IngestVisit` in the webapp. */
export type Visit = {
  /** Defaults to `new Date()` if omitted. */
  timestamp?: Date;
  pageUrl: string;
  userAgent?: string;
  referrer?: string;
  /**
   * The crawler's real connecting IP (not the visitor's — this route exists
   * for AI-crawler traffic). Used server-side to verify the user-agent's
   * claim by reverse DNS, then hashed and discarded; the raw address is
   * never stored. Omit only if truly unavailable — without it every hit
   * reports unverified.
   */
  clientIp?: string;
};

/** Mirrors `IngestResult` in the webapp, camelCased. */
export type IngestResult = {
  accepted: number;
  /** Malformed hits (no page URL, timestamp outside the retention window). */
  rejected: number;
  /** Hits past the project's daily cap. Never billed. */
  dropped: number;
  capReached: boolean;
};

export type AttensiraClientOptions = {
  /** Your project's id, as shown alongside the signing secret in `GET /v1/visits/install`. */
  projectId: string;
  /**
   * The per-project signing secret from `GET /v1/visits/install`'s
   * `signing_secret` field. Treat it like any other server-side credential:
   * environment variable, never committed, never sent to a client.
   */
  signingSecret: string;
  /** Override for staging/self-hosted setups. Defaults to the production ingest endpoint. */
  endpoint?: string;
  /** Injection point for tests; defaults to the global `fetch`. */
  fetch?: typeof fetch;
};

// -- signing ------------------------------------------------------------------

function toHex(buffer: ArrayBuffer): string {
  return [...new Uint8Array(buffer)].map((b) => b.toString(16).padStart(2, '0')).join('');
}

/**
 * Builds the `X-Attensira-Signature` header value: `t=<unix seconds>,v1=<hex
 * hmac-sha256>`, where the signed message is the literal bytes
 * `"<t>.<body>"` and the key is the project's signing secret used as UTF-8
 * bytes (not hex-decoded).
 *
 * This mirrors `verifySignature` / `projectSecret` in
 * `webapp/src/internal/aitraffic/ingest.go` byte-for-byte: same algorithm
 * (HMAC-SHA256), same encoding (lowercase hex), same signed-string
 * construction (`strconv.FormatInt(t, 10) + "."` followed by the raw body
 * bytes — equivalent to `` `${t}.${body}` `` since HMAC's streaming Write
 * calls are associative), and the same key material (the secret's raw
 * characters, exactly as `crypto.subtle.importKey('raw', ...)` is used in
 * the webapp's own generated worker snippet). See `index.test.ts` for a
 * test vector generated by re-running the Go implementation directly and
 * asserting byte-identical output here.
 */
export async function signBody(
  signingSecret: string,
  timestampSeconds: number,
  body: string
): Promise<string> {
  const key = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(signingSecret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  );
  const mac = await crypto.subtle.sign(
    'HMAC',
    key,
    new TextEncoder().encode(`${timestampSeconds}.${body}`)
  );
  return `t=${timestampSeconds},v1=${toHex(mac)}`;
}

// -- client -------------------------------------------------------------------

function serializeVisit(visit: Visit): Record<string, string> {
  return {
    timestamp: (visit.timestamp ?? new Date()).toISOString(),
    page_url: visit.pageUrl,
    user_agent: visit.userAgent ?? '',
    referrer: visit.referrer ?? '',
    client_ip: visit.clientIp ?? '',
  };
}

function parseIngestResult(raw: unknown): IngestResult {
  const r = (raw ?? {}) as Record<string, unknown>;
  return {
    accepted: typeof r.accepted === 'number' ? r.accepted : 0,
    rejected: typeof r.rejected === 'number' ? r.rejected : 0,
    dropped: typeof r.dropped === 'number' ? r.dropped : 0,
    capReached: r.cap_reached === true,
  };
}

/**
 * Header names commonly used to forward the real client IP through a proxy
 * or edge platform, checked in this order. `x-forwarded-for` may contain a
 * comma-separated chain; only the first (closest-to-client) hop is used.
 */
const CLIENT_IP_HEADERS = ['cf-connecting-ip', 'true-client-ip', 'x-real-ip'] as const;

/**
 * Best-effort extraction of the real connecting IP from a `Headers` object,
 * for platforms that don't already give you the raw socket address.
 */
export function getClientIp(headers: Headers): string {
  for (const name of CLIENT_IP_HEADERS) {
    const value = headers.get(name);
    if (value) return value.trim();
  }
  const forwardedFor = headers.get('x-forwarded-for');
  if (forwardedFor) {
    const first = forwardedFor.split(',')[0]?.trim();
    if (first) return first;
  }
  return '';
}

export class AttensiraClient {
  private readonly projectId: string;
  private readonly signingSecret: string;
  private readonly endpoint: string;
  private readonly fetchImpl: typeof fetch;

  constructor(options: AttensiraClientOptions) {
    assertServerSide();
    if (!options.projectId) {
      throw new Error('[@attensira/analytics] projectId is required');
    }
    if (!options.signingSecret) {
      throw new Error('[@attensira/analytics] signingSecret is required');
    }
    this.projectId = options.projectId;
    this.signingSecret = options.signingSecret;
    this.endpoint = options.endpoint ?? DEFAULT_ENDPOINT;
    this.fetchImpl = options.fetch ?? fetch;
  }

  /**
   * Signs and sends one batch (up to the webapp's 500-per-request limit;
   * this client does not chunk for you). Resolves with the server's
   * per-hit accounting, or rejects on a network error or a non-2xx
   * response — this never fails silently.
   */
  async sendVisits(visits: Visit | Visit[]): Promise<IngestResult> {
    const list = Array.isArray(visits) ? visits : [visits];
    if (list.length === 0) {
      throw new Error('[@attensira/analytics] sendVisits requires at least one visit');
    }

    const body = JSON.stringify({
      project_id: this.projectId,
      visits: list.map(serializeVisit),
    });
    const timestampSeconds = Math.floor(Date.now() / 1000);
    const signature = await signBody(this.signingSecret, timestampSeconds, body);

    const response = await this.fetchImpl(this.endpoint, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        [SIGNATURE_HEADER]: signature,
      },
      body,
    });

    const text = await response.text();
    if (!response.ok) {
      throw new Error(
        `[@attensira/analytics] ingest request failed: ${response.status} ${response.statusText} — ${text}`
      );
    }
    return parseIngestResult(text ? JSON.parse(text) : {});
  }

  /**
   * Convenience for the common case: build a `Visit` from an inbound
   * `Request` (page URL, user agent, referrer, and best-effort client IP)
   * and send it. Errors are logged, not thrown — a tracking failure must
   * never break the request it's attached to. Call this fire-and-forget
   * (in a Cloudflare Worker, wrap it in `ctx.waitUntil(...)`); await it
   * yourself if you need to know it landed.
   */
  async trackRequest(
    request: Request,
    extra: Partial<Visit> = {}
  ): Promise<IngestResult | undefined> {
    try {
      return await this.sendVisits({
        pageUrl: request.url,
        userAgent: request.headers.get('user-agent') ?? '',
        referrer: request.headers.get('referer') ?? '',
        clientIp: getClientIp(request.headers),
        ...extra,
      });
    } catch (error) {
      console.error('[@attensira/analytics] failed to send page hit:', error);
      return undefined;
    }
  }
}

/**
 * Creates a reusable client. Omit `options` to read `ATTENSIRA_PROJECT_ID`,
 * `ATTENSIRA_SIGNING_SECRET`, and (optionally) `ATTENSIRA_INGEST_ENDPOINT`
 * from `process.env`, for runtimes where that's available.
 */
export function createClient(options?: AttensiraClientOptions): AttensiraClient {
  if (options) return new AttensiraClient(options);

  const env = typeof process !== 'undefined' ? process.env : undefined;
  const projectId = env?.ATTENSIRA_PROJECT_ID;
  const signingSecret = env?.ATTENSIRA_SIGNING_SECRET;
  if (!projectId || !signingSecret) {
    throw new Error(
      '[@attensira/analytics] createClient() without options requires ' +
        'ATTENSIRA_PROJECT_ID and ATTENSIRA_SIGNING_SECRET in the environment'
    );
  }
  return new AttensiraClient({
    projectId,
    signingSecret,
    endpoint: env?.ATTENSIRA_INGEST_ENDPOINT,
  });
}
