import { test } from 'node:test';
import assert from 'node:assert/strict';
import { signBody, getClientIp, AttensiraClient } from './index.ts';

// -- signature: known-good vector from the Go implementation ----------------
//
// Generated by running the *actual* algorithm from
// webapp/src/internal/aitraffic/ingest.go (projectSecret + verifySignature)
// as a standalone Go program with fixed inputs — not reimplemented from
// memory. See the PR description for the Go source used to produce this
// vector. This is the single most important test in this file: a
// byte-for-byte match here is what tells us the webapp's HMAC verifier will
// actually accept what this client sends.
//
// Go run output:
//   root_key: test-root-signing-key
//   project_id: proj_test123
//   derived_secret (project_secret): 9746404dc283a0756805462d41e855837c0c663a2792fcec92a12bc1afef3641
//   timestamp: 1700000000
//   body: {"project_id":"proj_test123","visits":[{"timestamp":"2023-11-14T22:13:20Z","page_url":"https://example.com/","user_agent":"GPTBot/1.0","referrer":"","client_ip":"203.0.113.5"}]}
//   signature (v1): 1181046ff14a600d14cc358f2342d6a39879758b07c742746263d1ec4b5899e2
//   header: t=1700000000,v1=1181046ff14a600d14cc358f2342d6a39879758b07c742746263d1ec4b5899e2
const GO_VECTOR = {
  // This is projectSecret(rootKey, projectID) from ingest.go — i.e. the
  // value the webapp would hand back as `signing_secret` from
  // GET /v1/visits/install for this project. The client only ever sees
  // this derived value, never the root AI_TRAFFIC_SIGNING_KEY.
  signingSecret: '9746404dc283a0756805462d41e855837c0c663a2792fcec92a12bc1afef3641',
  timestampSeconds: 1700000000,
  body: '{"project_id":"proj_test123","visits":[{"timestamp":"2023-11-14T22:13:20Z","page_url":"https://example.com/","user_agent":"GPTBot/1.0","referrer":"","client_ip":"203.0.113.5"}]}',
  expectedHeader:
    't=1700000000,v1=1181046ff14a600d14cc358f2342d6a39879758b07c742746263d1ec4b5899e2',
};

test('signBody matches the Go verifier byte-for-byte for a known vector', async () => {
  const header = await signBody(GO_VECTOR.signingSecret, GO_VECTOR.timestampSeconds, GO_VECTOR.body);
  assert.equal(header, GO_VECTOR.expectedHeader);
});

test('signBody is deterministic and sensitive to every input', async () => {
  const base = await signBody('secret', 100, '{"a":1}');
  const differentSecret = await signBody('other-secret', 100, '{"a":1}');
  const differentTimestamp = await signBody('secret', 101, '{"a":1}');
  const differentBody = await signBody('secret', 100, '{"a":2}');

  assert.notEqual(base, differentSecret);
  assert.notEqual(base, differentTimestamp);
  assert.notEqual(base, differentBody);

  const repeat = await signBody('secret', 100, '{"a":1}');
  assert.equal(base, repeat);
});

test('signBody header has the exact "t=<int>,v1=<64 lowercase hex>" shape', async () => {
  const header = await signBody('secret', 42, '{}');
  const match = /^t=(\d+),v1=([0-9a-f]{64})$/.exec(header);
  assert.ok(match, `header did not match expected shape: ${header}`);
});

// -- getClientIp --------------------------------------------------------------

test('getClientIp prefers cf-connecting-ip', () => {
  const headers = new Headers({
    'cf-connecting-ip': '1.1.1.1',
    'x-forwarded-for': '2.2.2.2, 3.3.3.3',
  });
  assert.equal(getClientIp(headers), '1.1.1.1');
});

test('getClientIp falls back to the first x-forwarded-for hop', () => {
  const headers = new Headers({ 'x-forwarded-for': '2.2.2.2, 3.3.3.3' });
  assert.equal(getClientIp(headers), '2.2.2.2');
});

test('getClientIp returns empty string when nothing is present', () => {
  assert.equal(getClientIp(new Headers()), '');
});

// -- AttensiraClient.sendVisits: request shape ---------------------------------

test('sendVisits POSTs the exact body/header shape the webapp expects', async () => {
  let capturedUrl: string | undefined;
  let capturedInit: RequestInit | undefined;

  const fakeFetch = (async (url: string | URL, init?: RequestInit) => {
    capturedUrl = String(url);
    capturedInit = init;
    return new Response(
      JSON.stringify({ accepted: 1, rejected: 0, dropped: 0, cap_reached: false }),
      { status: 202, headers: { 'content-type': 'application/json' } }
    );
  }) as typeof fetch;

  const client = new AttensiraClient({
    projectId: 'proj_test123',
    signingSecret: 'shh',
    fetch: fakeFetch,
  });

  const result = await client.sendVisits({
    pageUrl: 'https://example.com/',
    userAgent: 'GPTBot/1.0',
    clientIp: '203.0.113.5',
  });

  assert.equal(capturedUrl, 'https://api.attensira.com/v1/visits');
  assert.equal(capturedInit?.method, 'POST');

  const headers = capturedInit?.headers as Record<string, string>;
  assert.equal(headers['content-type'], 'application/json');
  assert.ok(/^t=\d+,v1=[0-9a-f]{64}$/.test(headers['X-Attensira-Signature']));

  const body = JSON.parse(capturedInit?.body as string);
  assert.equal(body.project_id, 'proj_test123');
  assert.equal(body.visits.length, 1);
  assert.equal(body.visits[0].page_url, 'https://example.com/');
  assert.equal(body.visits[0].user_agent, 'GPTBot/1.0');
  assert.equal(body.visits[0].client_ip, '203.0.113.5');
  assert.equal(body.visits[0].referrer, '');
  assert.ok(typeof body.visits[0].timestamp === 'string');

  assert.deepEqual(result, { accepted: 1, rejected: 0, dropped: 0, capReached: false });
});

test('the signature sendVisits produces verifies against the exact body it sends', async () => {
  // This closes the loop: rather than trusting signBody in isolation, catch
  // the exact body sendVisits serialized and the exact header it attached,
  // then recompute the signature independently and confirm they match —
  // the same check the webapp's verifySignature does server-side.
  let capturedBody: string | undefined;
  let capturedSignatureHeader: string | undefined;

  const fakeFetch = (async (_url: string | URL, init?: RequestInit) => {
    capturedBody = init?.body as string;
    capturedSignatureHeader = (init?.headers as Record<string, string>)['X-Attensira-Signature'];
    return new Response(JSON.stringify({ accepted: 1, rejected: 0, dropped: 0, cap_reached: false }), {
      status: 202,
    });
  }) as typeof fetch;

  const secret = 'a-project-signing-secret';
  const client = new AttensiraClient({ projectId: 'proj_x', signingSecret: secret, fetch: fakeFetch });
  await client.sendVisits({ pageUrl: 'https://example.com/a' });

  assert.ok(capturedBody);
  assert.ok(capturedSignatureHeader);

  const [, tStr] = /^t=(\d+),v1=[0-9a-f]{64}$/.exec(capturedSignatureHeader!)!;
  const recomputed = await signBody(secret, Number(tStr), capturedBody!);
  assert.equal(recomputed, capturedSignatureHeader);
});

test('sendVisits rejects on a non-2xx response instead of failing silently', async () => {
  const fakeFetch = (async () => new Response('bad signature', { status: 401 })) as typeof fetch;
  const client = new AttensiraClient({ projectId: 'p', signingSecret: 's', fetch: fakeFetch });
  await assert.rejects(() => client.sendVisits({ pageUrl: 'https://example.com/' }), /401/);
});

test('sendVisits rejects with no visits', async () => {
  const client = new AttensiraClient({ projectId: 'p', signingSecret: 's', fetch: (async () => new Response()) as typeof fetch });
  await assert.rejects(() => client.sendVisits([]));
});

// -- trackRequest ---------------------------------------------------------------

test('trackRequest derives page_url/user_agent/referrer/client_ip from a Request', async () => {
  let capturedBody: string | undefined;
  const fakeFetch = (async (_url: string | URL, init?: RequestInit) => {
    capturedBody = init?.body as string;
    return new Response(JSON.stringify({ accepted: 1, rejected: 0, dropped: 0, cap_reached: false }), {
      status: 202,
    });
  }) as typeof fetch;

  const client = new AttensiraClient({ projectId: 'p', signingSecret: 's', fetch: fakeFetch });
  const request = new Request('https://customer-site.com/blog/post', {
    headers: {
      'user-agent': 'ClaudeBot/1.0',
      referer: 'https://google.com/',
      'cf-connecting-ip': '198.51.100.9',
    },
  });

  const result = await client.trackRequest(request);
  assert.ok(result);
  assert.equal(result?.accepted, 1);

  const body = JSON.parse(capturedBody!);
  assert.equal(body.visits[0].page_url, 'https://customer-site.com/blog/post');
  assert.equal(body.visits[0].user_agent, 'ClaudeBot/1.0');
  assert.equal(body.visits[0].referrer, 'https://google.com/');
  assert.equal(body.visits[0].client_ip, '198.51.100.9');
});

test('trackRequest swallows failures and logs instead of throwing', async () => {
  const fakeFetch = (async () => new Response('nope', { status: 500 })) as typeof fetch;
  const client = new AttensiraClient({ projectId: 'p', signingSecret: 's', fetch: fakeFetch });
  const request = new Request('https://customer-site.com/');
  const result = await client.trackRequest(request);
  assert.equal(result, undefined);
});

// -- constructor validation ------------------------------------------------------

test('constructor requires projectId and signingSecret', () => {
  assert.throws(() => new AttensiraClient({ projectId: '', signingSecret: 's' }));
  assert.throws(() => new AttensiraClient({ projectId: 'p', signingSecret: '' }));
});
